### ISSUE TITLE
note for me

### ISSUE THREAD

**Issue by KazuCocoa** [KazuCocoa/AppiumRegressionCheck#1]
branch: https://github.com/KazuCocoa/ruby_lib_core/tree/realdevice

---

- https://github.com/appium/appium-xcuitest-driver
- https://github.com/appium/appium-xcuitest-driver/blob/35523f0ed637418e19bc84373dfb4bf59903c75c/lib/wda/webdriveragent.js
- https://github.com/appium/appium-xcuitest-driver/blob/4c12c3d9e0eedc9f9f6908b0f038433495c722c6/docs/real-device-config.md
- https://github.com/appium/appium/blob/3ec103fb235b8d7eb307d6b3921664ea049b99b7/docs/en/drivers/ios-xcuitest.md

---

```
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing running processes 'xcodebuild.*242bfcc998fd156df0bd0ad1dde8ab8e0a032114, iproxy 8100' for the device 242bfcc998fd156df0bd0ad1dde8ab8e0a032114...
[debug] [XCUITest] 'pgrep -nif xcodebuild.*242bfcc998fd156df0bd0ad1dde8ab8e0a032114' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] 'pgrep -nif iproxy 8100' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [XCUITest] Using Xcode 9.2, so fixing WDA codebase
[debug] [XCUITest] Successfully updated '/Users/kazuaki/.nodebrew/node/v9.3.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj/project.pbxproj' with bundle id 'com.apple.test.WebDriverAgentRunner-Runner'
[debug] [XCUITest] Generating xcode config file for orgId 'Z96JDV3GJT' and signingId 'iPhone Developer'
[debug] [XCUITest] Writing xcode config file to /var/folders/y6/524wp8fx0xj5q1rf6fktjrb00000gn/T/2018211-41605-1pkzpvk.qrfu/appium-temp.xcconfig
[XCUITest] Cannot parse major and minor version numbers from platformVersion "null". Will build for the default platform instead
[debug] [XCUITest] Using Xcode configuration file: '/var/folders/y6/524wp8fx0xj5q1rf6fktjrb00000gn/T/2018211-41605-1pkzpvk.qrfu/appium-temp.xcconfig'
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Users/kazuaki/.nodebrew/node/v9.3.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=242bfcc998fd156df0bd0ad1dde8ab8e0a032114 -xcconfig /var/folders/y6/524wp8fx0xj5q1rf6fktjrb00000gn/T/2018211-41605-1pkzpvk.qrfu/appium-temp.xcconfig' in directory '/Users/kazuaki/.nodebrew/node/v9.3.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged. To see xcode logging, use 'showXcodeLog' desired capability
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] 2018-03-11 23:34:27.103 xcodebuild[41808:2927321] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder “WebDriverAgentRunner_iphoneos11.2-arm64.xctestrun” doesn’t exist." UserInfo={NSFilePath=/Users/kazuaki/Library/Developer/Xcode/DerivedData/WebDriverAgent-blubpazyhvxyybbhzwfqrgjgtptv/Build/Products/WebDriverAgentRunner_iphoneos11.2-arm64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7faea9b6c7a0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode]
[Xcode] 2018-03-11 23:34:27.104 xcodebuild[41808:2927321] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder “WebDriverAgentRunner_iphoneos11.2-arm64.xctestrun” doesn’t exist." UserInfo={NSFilePath=/Users/kazuaki/Library/Developer/Xcode/DerivedData/WebDriverAgent-blubpazyhvxyybbhzwfqrgjgtptv/Build/Products/WebDriverAgentRunner_iphoneos11.2-arm64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7faea9adf390 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode]
[Xcode]
[Xcode]
[Xcode] ** TEST BUILD FAILED **
[Xcode]
[Xcode]
[Xcode]
[Xcode] The following build commands failed:
[Xcode]
[Xcode] 	Check dependencies
[Xcode]
[Xcode] (1 failure)
[Xcode]
[debug] [XCUITest] Log file for xcodebuild test: /var/folders/y6/524wp8fx0xj5q1rf6fktjrb00000gn/T/com.apple.dt.XCTest/IDETestRunSession-FF0093A8-3512-4019-86B4-7606CFAF71A7/WebDriverAgentRunner-2D50A8D4-A6E1-421A-98EA-7AF0B631474E/Session-WebDriverAgentRunner-2018-03-11_233427-MrqG4K.log
[Xcode] 2018-03-11 23:34:27.153 xcodebuild[41808:2927321]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
[Xcode] /var/folders/y6/524wp8fx0xj5q1rf6fktjrb00000gn/T/com.apple.dt.XCTest/IDETestRunSession-FF0093A8-3512-4019-86B4-7606CFAF71A7/WebDriverAgentRunner-2D50A8D4-A6E1-421A-98EA-7AF0B631474E/Session-WebDriverAgentRunner-2018-03-11_233427-MrqG4K.log
[Xcode]
[Xcode] 2018-03-11 23:34:27.154 xcodebuild[41808:2927174] [MT] IDETestOperationsObserverDebug: (EEA06517-8841-4744-BA17-BDDFAD6BC8EC) Beginning test session WebDriverAgentRunner-EEA06517-8841-4744-BA17-BDDFAD6BC8EC at 2018-03-11 23:34:27.153 with Xcode 9C40b on target <DVTiOSDevice: 0x7faea98fa140> {
[Xcode] 		deviceSerialNumber:         C39RK27FH2XP
[Xcode] 		identifier:                 242bfcc998fd156df0bd0ad1dde8ab8e0a032114
[Xcode] 		deviceClass:                iPhone
[Xcode] 		deviceName:                 Kazu's iPhone SE
[Xcode] 		deviceIdentifier:           242bfcc998fd156df0bd0ad1dde8ab8e0a032114
[Xcode] 		productVersion:             11.2.6
[Xcode] 		buildVersion:               15D100
[Xcode] 		deviceSoftwareVersion:      11.2.6 (15D100)
[Xcode] 		deviceArchitecture:         arm64
[Xcode] 		deviceTotalCapacity:        60619866112
[Xcode] 		deviceAvailableCapacity:    7718395904
[Xcode] 		deviceIsTransient:          NO
[Xcode] 		ignored:                    NO
[Xcode] 		deviceIsBusy:               NO
[Xcode] 		deviceIsActivated:          YES
[Xcode] 		deviceActivationState:      Activated
[Xcode] 		isPasscodeLocked:           NO
[Xcode] 		deviceType:                 <DVTDeviceType:0x7faea9602f10 Xcode.DeviceType.iPhone>
[Xcode] 		supportedDeviceFamilies:    (
[Xcode]     1
[Xcode] )
[Xcode] 		applications:              (null)
[Xcode] 		provisioningProfiles:      (null)
[Xcode] 		hasInternalSupport:        NO
[Xcode] 		isSupportedOS:             YES
[Xcode] 		developerDiskMountError:   (null)
[Xcode] (null)
[Xcode] 	bootArgs:                  <unavailable>
[Xcode] 		connected:                 yes
[Xcode] 		isWirelessEnabled:         no
[Xcode] 		connectionType:            direct
[Xcode] 		} (11.2.6 (15D100))
[Xcode]
[Xcode] 2018-03-11 23:34:27.213 xcodebuild[41808:2927174] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/kazuaki/Library/Developer/Xcode/DerivedData/WebDriverAgent-blubpazyhvxyybbhzwfqrgjgtptv/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7faea9d8a180 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode]
[Xcode] 2018-03-11 23:34:27.213 xcodebuild[41808:2927174] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode]
[Xcode] ** TEST EXECUTE FAILED **
[Xcode]
[Xcode]
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1520778867241 (23:34:27 GMT+0900 (JST))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 41807)
[debug] [XCUITest] iproxy exited with code 'null'
[debug] [XCUITest] Successfully reset '/Users/kazuaki/.nodebrew/node/v9.3.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj/project.pbxproj' with bundle id 'com.facebook.WebDriverAgentRunner'
[debug] [XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at XCUITestDriver.quitAndUninstall$ (/Users/kazuaki/.nodebrew/node/v9.3.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:375:13)
    at tryCatch (/Users/kazuaki/.nodebrew/node/v9.3.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/kazuaki/.nodebrew/node/v9.3.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/kazuaki/.nodebrew/node/v9.3.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/kazuaki/.nodebrew/node/v9.3.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
 Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at XCUITestDriver.quitAndUninstall$ (/Users/kazuaki/.nodebrew/node/v9.3.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:375:13)
    at tryCatch (/Users/kazuaki/.nodebrew/node/v9.3.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/kazuaki/.nodebrew/node/v9.3.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/kazuaki/.nodebrew/node/v9.3.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/kazuaki/.nodebrew/node/v9.3.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at XCUITestDriver.quitAndUninstall$ (/Users/kazuaki/.nodebrew/node/v9.3.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:375:13)
    at tryCatch (/Users/kazuaki/.nodebrew/node/v9.3.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/kazuaki/.nodebrew/node/v9.3.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/kazuaki/.nodebrew/node/v9.3.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/kazuaki/.nodebrew/node/v9.3.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
[HTTP] <-- POST /wd/hub/session 500 13334 ms - 470
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"ios","automationName":"XCUITest","bundleId":"com.apple.calculator","deviceName":"Kazu's iPhone SE","udid":"242bfcc998fd156df0bd0ad1dde8ab8e0a032114","someCapability":"some_capability","xcodeOrgId":"Z96JDV3GJT","xcodeSigningId":"iPhone Developer","updatedWDABundleId":"com.apple.test.WebDriverAgentRunner-Runner","wdaLocalPort":8100,"noReset":true,"fullReset":false,"useNewWDA":false},"capabilities":{"alwaysMatch":{"platformName":"ios","appium:automationName":"XCUITest","appium:bundleId":"com.apple.calculator","appium:deviceName":"Kazu's iPhone SE","appium:udid":"242bfcc998fd156df0bd0ad1dde8ab8e0a032114","appium:someCapability":"some_capability","appium:xcodeOrgId":"Z96JDV3GJT","appium:xcodeSigningId":"iPhone Developer","appium:updatedWDABundleId":"com.apple.test.WebDriverAgentRunner-Runner","appium:wdaLocalPort":8100,"appium:noReset":true,"appium:fullReset":false,"appium:useNewWDA":false},"firstMatch":[{}]}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"ios","automationName":"XCUITest","bundleId":"com.apple.calculator","deviceName":"Kazu's iPhone SE","udid":"242bfcc998fd156df0bd0ad1dde8ab8e0a032114","someCapability":"some_capability","xcodeOrgId":"Z96JDV3GJT","xcodeSigningId":"iPhone Developer","updatedWDABundleId":"com.apple.test.WebDriverAgentRunner-Runner","wdaLocalPort":8100,"noReset":true,"fullReset":false,"useNewWDA":false},null,{"alwaysMatch":{"platformName":"ios","appium:automationName":"XCUITest","appium:bundleId":"com.apple.calculator","appium:deviceName":"Kazu's iPhone SE","appium:udid":"242bfcc998fd156df0bd0ad1dde8ab8e0a032114","appium:someCapability":"some_capability","appium:xcodeOrgId":"Z96JDV3GJT","appium:xcodeSigningId":"iPhone Developer","appium:updatedWDABundleId":"com.apple.test.WebDriverAgentRunner-Runner","appium:wdaLocalPort":8100,"appium:noReset":true,"appium:fullReset":false,"appium:useNewWDA":false},"firstMatch":[{}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1520778867687 (23:34:27 GMT+0900 (JST))
[Appium] Merged W3C capabilities {"alwaysMatch":{"platformName":"ios","appium:au... into desiredCapabilities object {"platformName":"ios","automationName":"XCUITes...
```

**Comment by KazuCocoa** [comment]
```
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] 2018-03-12 00:23:26.121 xcodebuild[43953:2972602] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode]
[Xcode] ** TEST EXECUTE FAILED **
[Xcode]
[Xcode]
```

**Comment by KazuCocoa** [comment]
```
[Xcode] 2018-03-12 00:27:47.214 xcodebuild[44176:2978381]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
[Xcode] /var/folders/y6/524wp8fx0xj5q1rf6fktjrb00000gn/T/com.apple.dt.XCTest/IDETestRunSession-AC9813A3-4BBA-4F7A-B583-BC628A7664F8/WebDriverAgentRunner-75B5D7E6-0D45-487C-BFD7-72BAF709FA1B/Session-WebDriverAgentRunner-2018-03-12_002747-NCDqT2.log
[Xcode]
[Xcode] 2018-03-12 00:27:47.216 xcodebuild[44176:2978310] [MT] IDETestOperationsObserverDebug: (1F5FF5D1-6FD7-4D74-B349-A71AC95ACA60) Beginning test session WebDriverAgentRunner-1F5FF5D1-6FD7-4D74-B349-A71AC95ACA60 at 2018-03-12 00:27:47.215 with Xcode 9C40b on target <DVTiOSDevice: 0x7ff3feef28d0> {
[Xcode] 		deviceSerialNumber:         C39RK27FH2XP
[Xcode] 		identifier:                 242bfcc998fd156df0bd0ad1dde8ab8e0a032114
[Xcode] 		deviceClass:                iPhone
[Xcode] 		deviceName:                 Kazu's iPhone SE
[Xcode] 		deviceIdentifier:           242bfcc998fd156df0bd0ad1dde8ab8e0a032114
[Xcode] 		productVersion:             11.2.6
[Xcode] 		buildVersion:               15D100
[Xcode] 		deviceSoftwareVersion:      11.2.6 (15D100)
[Xcode] 		deviceArchitecture:         arm64
[Xcode] 		deviceTotalCapacity:        60619866112
[Xcode] 		deviceAvailableCapacity:    7665426432
[Xcode] 		deviceIsTransient:          NO
[Xcode] 		ignored:                    NO
[Xcode] 		deviceIsBusy:               NO
[Xcode] 		deviceIsActivated:          YES
[Xcode] 		deviceActivationState:      Activated
[Xcode] 		isPasscodeLocked:           NO
[Xcode] 		deviceType:                 <DVTDeviceType:0x7ff3fc4ac300 Xcode.DeviceType.iPhone>
[Xcode] 		supportedDeviceFamilies:    (
[Xcode]     1
[Xcode] )
[Xcode] 		applications:              (null)
[Xcode] 		provisioningProfiles:      (null)
[Xcode] 		hasInternalSupport:        NO
[Xcode] 		isSupportedOS:             YES
[Xcode] 		developerDiskMountError:   (null)
[Xcode] (null)
[Xcode] 	bootArgs:                  <unavailable>
[Xcode] 		connected:                 yes
[Xcode] 		isWirelessEnabled:         no
[Xcode] 		connectionType:            direct
[Xcode] 		} (11.2.6 (15D100))
[Xcode]
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/y6/524wp8fx0xj5q1rf6fktjrb00000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/8b7966400bf380ea702df21e50af5253/242bfcc998fd156df0bd0ad1dde8ab8e0a032114/ManifestCache.plist
[Xcode]
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] 2018-03-12 00:27:55.447 xcodebuild[44176:2978310] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode]
[Xcode] ** TEST EXECUTE FAILED **
[Xcode]
[Xcode]
[Xcode] 2018-03-12 00:27:55.216949+0900 WebDriverAgentRunner-Runner[432:30494] +[CATransaction synchronize] called within transaction
[Xcode] 2018-03-12 00:27:55.292003+0900 WebDriverAgentRunner-Runner[432:30494] Running tests...
[Xcode] 2018-03-12 00:27:55.361435+0900 WebDriverAgentRunner-Runner[432:30494] The bundle “WebDriverAgentRunner” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
[Xcode] 2018-03-12 00:27:55.361571+0900 WebDriverAgentRunner-Runner[432:30494] (dlopen_preflight(/var/containers/Bundle/Application/D7B6E9F8-8969-4A81-845B-7751C41A2B63/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner): Library not loaded: @rpath/RoutingHTTPServer.framework/RoutingHTTPServer
[Xcode]   Referenced from: /private/var/containers/Bundle/Application/D7B6E9F8-8969-4A81-845B-7751C41A2B63/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib
[Xcode]   Reason: no suitable image found.  Did find:
[Xcode] 	/private/var/containers/Bundle/Application/D7B6E9F8-8969-4A81-845B-7751C41A2B63/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer: required code signature missing for '/private/var/containers/Bundle/Application/D7B6E9F8-8969-4A81-845B-7751C41A2B63/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer'
[Xcode] )
[Xcode]
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[Xcode] Contents of xcodebuild log file '/var/folders/y6/524wp8fx0xj5q1rf6fktjrb00000gn/T/com.apple.dt.XCTest/IDETestRunSession-AC9813A3-4BBA-4F7A-B583-BC628A7664F8/WebDriverAgentRunner-75B5D7E6-0D45-487C-BFD7-72BAF709FA1B/Session-WebDriverAgentRunner-2018-03-12_002747-NCDqT2.log':
[Xcode] 00:27:47.216 xcodebuild[44176:2978310] Beginning test session WebDriverAgentRunner-1F5FF5D1-6FD7-4D74-B349-A71AC95ACA60 at 2018-03-12 00:27:47.215 with Xcode 9C40b on target <DVTiOSDevice: 0x7ff3feef28d0> {
[Xcode] 		deviceSerialNumber:         C39RK27FH2XP
[Xcode] 		identifier:                 242bfcc998fd156df0bd0ad1dde8ab8e0a032114
[Xcode] 		deviceClass:                iPhone
[Xcode] 		deviceName:                 Kazu's iPhone SE
[Xcode] 		deviceIdentifier:           242bfcc998fd156df0bd0ad1dde8ab8e0a032114
[Xcode] 		productVersion:             11.2.6
[Xcode] 		buildVersion:               15D100
[Xcode] 		deviceSoftwareVersion:      11.2.6 (15D100)
[Xcode] 		deviceArchitecture:         arm64
[Xcode] 		deviceTotalCapacity:        60619866112
[Xcode] 		deviceAvailableCapacity:    7665426432
[Xcode] 		deviceIsTransient:          NO
[Xcode] 		ignored:                    NO
[Xcode] 		deviceIsBusy:               NO
[Xcode] 		deviceIsActivated:          YES
[Xcode] 		deviceActivationState:      Activated
[Xcode] 		isPasscodeLocked:           NO
[Xcode] 		deviceType:                 <DVTDeviceType:0x7ff3fc4ac300 Xcode.DeviceType.iPhone>
[Xcode] 		supportedDeviceFamilies:    (
[Xcode]     1
[Xcode] )
[Xcode] 		applications:              (null)
[Xcode] 		provisioningProfiles:      (null)
[Xcode] 		hasInternalSupport:        NO
[Xcode] 		isSupportedOS:             YES
[Xcode] 		developerDiskMountError:   (null)
[Xcode] (null)
[Xcode] 	bootArgs:                  <unavailable>
[Xcode] 		connected:                 yes
[Xcode] 		isWirelessEnabled:         no
[Xcode] 		connectionType:            direct
[Xcode] 		} (11.2.6 (15D100))
[Xcode] 00:27:47.217 xcodebuild[44176:2978310] 	/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild
[Xcode] build-for-testing
[Xcode] test-without-building
[Xcode] -project
[Xcode] /Users/kazuaki/GitHub/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj
[Xcode] -scheme
```

**Comment by KazuCocoa** [comment]
I could work following https://github.com/appium/appium-xcuitest-driver/blob/4c12c3d9e0eedc9f9f6908b0f038433495c722c6/docs/real-device-config.md#basic-automatic-configuration

**Comment by KazuCocoa** [comment]
https://github.com/KazuCocoa/ruby_lib_core/tree/investigate-realdevice-simulator-switch

**Comment by KazuCocoa** [comment]
## Problem

- Previous port's WDA work

1. Launch with **A** and stop the test
    - Then a simulator is launched with port `8101`
2. Launch with **B**
    - Then tests run with **A** environment with port `8101`

## Why
Appium checks the WDA status with `status` command `http://localhost:8101/status`. If the port is used and the WDA response to the device, Appium continue to communicate with the WDA.
It sometimes leads the above problem. To avoid the case, we should change the port every time. And if it the port is unused, we should stop the port.

https://github.com/appium/appium-xcuitest-driver


- A: Simulator
```
    IOS_OPS = {
      caps: {
        platformName: :ios,
        automationName: 'XCUITest',
        platformVersion: '11.2',
        bundleId: 'com.apple.mobilecal',
        # deviceName: 'iPhone Simulator', # for simulator
        deviceName: "Kazu's iPhone SE", # For a real device
        udid: 'auto',                   # For a real device
        xcodeOrgId: 'zzzzzz',
        xcodeSigningId: 'iPhone Developer',
        updatedWDABundleId: 'com.kazucocoa.WebDriverAgentRunner',
        wdaLocalPort: 8101 # Change the port
      },
```

- B: Real Device
```
    IOS_OPS = {
      caps: {
        platformName: :ios,
        automationName: 'XCUITest',
        platformVersion: '11.2',
        bundleId: 'com.apple.mobilecal',
        # deviceName: 'iPhone Simulator', # for simulator
        deviceName: "Kazu's iPhone SE", # For a real device
        udid: 'auto',                   # For a real device
        xcodeOrgId: 'zzzzzz',
        xcodeSigningId: 'iPhone Developer',
        updatedWDABundleId: 'com.kazucocoa.WebDriverAgentRunner',
        wdaLocalPort: 8101 # Change the port
      },
```

**Comment by KazuCocoa** [comment]
Should we restrict the running WDA with some capabilities?

**Comment by KazuCocoa** [comment]
Run tests on the same device even caps are different, if the port of WDA running #2
